# Home Assistant Automation Blueprint: Stromüberwachung und Aktionen
blueprint:
  name: Stromüberwachung und Aktionen
  description: Löst Aktionen aus, wenn der verfügbare Strom für mehr als x Minuten einen bestimmten negativen Wert überschreitet oder unterschreitet.
  domain: automation
  input:
    power_sensor:
      name: Stromsensor
      description: Sensor, der den verfügbaren Strom misst (negativer Wert)
      selector:
        entity:
          domain: sensor
    threshold_on:
      name: Schwellenwert Einschalten
      description: Der Schwellenwert des verfügbaren Stroms zum Einschalten (negativer Wert)
      default: -1000
      selector:
        number:
          min: -10000
          max: 0
          unit_of_measurement: W
    threshold_off:
      name: Schwellenwert Ausschalten
      description: Der Schwellenwert des verfügbaren Stroms zum Ausschalten (negativer Wert)
      default: -500
      selector:
        number:
          min: -10000
          max: 0
          unit_of_measurement: W
    duration_above:
      name: Dauer in Minuten für Überschreiten
      description: Die Dauer, für die der Schwellenwert überschritten werden muss
      default: 5
      selector:
        number:
          min: 1
          max: 60
          unit_of_measurement: minutes
    duration_below:
      name: Dauer in Minuten für Unterschreiten
      description: Die Dauer, für die der Schwellenwert unterschritten werden muss
      default: 5
      selector:
        number:
          min: 1
          max: 60
          unit_of_measurement: minutes
    above_action:
      name: Aktion bei Überschreiten
      description: Aktion, die ausgeführt wird, wenn der verfügbare Strom den negativen Schwellenwert zum Einschalten überschreitet (weniger negativ)
      selector:
        action:
    below_action:
      name: Aktion bei Unterschreiten
      description: Aktion, die ausgeführt wird, wenn der verfügbare Strom den negativen Schwellenwert zum Ausschalten unterschreitet (mehr negativ)
      selector:
        action:

trigger:
  - platform: numeric_state
    entity_id: !input 'power_sensor'
    above: !input 'threshold_on'
    for:
      minutes: !input 'duration_above'
  - platform: numeric_state
    entity_id: !input 'power_sensor'
    below: !input 'threshold_off'
    for:
      minutes: !input 'duration_below'

action:
  - choose:
      - conditions:
          - condition: numeric_state
            entity_id: !input 'power_sensor'
            above: !input 'threshold_on'
        sequence: !input 'above_action'
      - conditions:
          - condition: numeric_state
            entity_id: !input 'power_sensor'
            below: !input 'threshold_off'
        sequence: !input 'below_action'
