blueprint:
  name: ZHA Remote – Aktionen pro Event (mit Long-Press Loop)
  description: >
    Robuster Blueprint für ZHA Remotes über zha_event.
    Pro Event (short/long/release up/down) können Sequenzen definiert werden.
    Long-Press kann in einer Loop wiederholt werden, bis Release kommt (mode restart).
  domain: automation

  input:
    zha_device:
      name: ZHA Gerät
      selector:
        device:
          integration: zha

    on_short_actions:
      name: Short Up (ON)
      default: []
      selector:
        action: {}

    off_short_actions:
      name: Short Down (OFF)
      default: []
      selector:
        action: {}

    up_long_start_actions:
      name: Long Up – Start (einmalig)
      default: []
      selector:
        action: {}

    up_long_loop_actions:
      name: Long Up – Loop (wiederholt)
      default: []
      selector:
        action: {}

    up_release_actions:
      name: Release Up
      default: []
      selector:
        action: {}

    down_long_start_actions:
      name: Long Down – Start (einmalig)
      default: []
      selector:
        action: {}

    down_long_loop_actions:
      name: Long Down – Loop (wiederholt)
      default: []
      selector:
        action: {}

    down_release_actions:
      name: Release Down
      default: []
      selector:
        action: {}

    loop_enabled:
      name: Loop aktivieren
      default: true
      selector:
        boolean: {}

    loop_delay_ms:
      name: Loop Intervall (ms)
      default: 250
      selector:
        number:
          min: 50
          max: 2000
          step: 50
          unit_of_measurement: ms
          mode: slider

    loop_max_repeats:
      name: Maximale Loop-Wiederholungen
      default: 500
      selector:
        number:
          min: 1
          max: 2000
          step: 1
          mode: slider

    match_up_short:
      name: Match Up Short (eine Zeile pro String)
      default: "on"
      selector:
        text:
          multiline: true

    match_down_short:
      name: Match Down Short (eine Zeile pro String)
      default: "off"
      selector:
        text:
          multiline: true

    match_up_long:
      name: Match Up Long (eine Zeile pro String)
      default: |-
        move_with_on_off_0_83
        move_with_on_off_MoveMode.Up_83
      selector:
        text:
          multiline: true

    match_down_long:
      name: Match Down Long (eine Zeile pro String)
      default: |-
        move_1_83
        move_MoveMode.Down_83_bitmap8.0_bitmap8.0
      selector:
        text:
          multiline: true

    match_up_release:
      name: Match Up Release (eine Zeile pro String)
      default: |-
        stop_with_on_off
        stop
      selector:
        text:
          multiline: true

    match_down_release:
      name: Match Down Release (eine Zeile pro String)
      default: |-
        stop_with_on_off
        stop
      selector:
        text:
          multiline: true

mode: restart
max_exceeded: silent

trigger:
  - platform: event
    event_type: zha_event
    event_data:
      device_id: !input zha_device

variables:
  action_str: >-
    {{ trigger.event.data.command ~
       ( '_' if (trigger.event.data.args is defined and (trigger.event.data.args|length > 0)) else '' ) ~
       ( trigger.event.data.args|join('_') if (trigger.event.data.args is defined) else '' )
    }}

  up_short_list: >-
    {{ match_up_short.splitlines() | map('trim') | reject('equalto','') | list }}
  down_short_list: >-
    {{ match_down_short.splitlines() | map('trim') | reject('equalto','') | list }}
  up_long_list: >-
    {{ match_up_long.splitlines() | map('trim') | reject('equalto','') | list }}
  down_long_list: >-
    {{ match_down_long.splitlines() | map('trim') | reject('equalto','') | list }}
  up_release_list: >-
    {{ match_up_release.splitlines() | map('trim') | reject('equalto','') | list }}
  down_release_list: >-
    {{ match_down_release.splitlines() | map('trim') | reject('equalto','') | list }}

action:
  - choose:
      - conditions:
          - condition: template
            value_template: "{{ action_str in up_short_list }}"
        sequence: !input on_short_actions

      - conditions:
          - condition: template
            value_template: "{{ action_str in down_short_list }}"
        sequence: !input off_short_actions

      - conditions:
          - condition: template
            value_template: "{{ action_str in up_long_list }}"
        sequence:
          - sequence: !input up_long_start_actions
          - choose:
              - conditions:
                  - condition: template
                    value_template: "{{ loop_enabled | bool }}"
                sequence:
                  - repeat:
                      while:
                        - condition: template
                          value_template: "{{ repeat.index <= (loop_max_repeats | int) }}"
                      sequence:
                        - sequence: !input up_long_loop_actions
                        - delay:
                            milliseconds: !input loop_delay_ms
            default:
              - sequence: !input up_long_loop_actions

      - conditions:
          - condition: template
            value_template: "{{ action_str in down_long_list }}"
        sequence:
          - sequence: !input down_long_start_actions
          - choose:
              - conditions:
                  - condition: template
                    value_template: "{{ loop_enabled | bool }}"
                sequence:
                  - repeat:
                      while:
                        - condition: template
                          value_template: "{{ repeat.index <= (loop_max_repeats | int) }}"
                      sequence:
                        - sequence: !input down_long_loop_actions
                        - delay:
                            milliseconds: !input loop_delay_ms
            default:
              - sequence: !input down_long_loop_actions

      - conditions:
          - condition: template
            value_template: "{{ action_str in up_release_list }}"
        sequence: !input up_release_actions

      - conditions:
          - condition: template
            value_template: "{{ action_str in down_release_list }}"
        sequence: !input down_release_actions
