blueprint:
  name: ZHA IKEA E1743 – Aktionen pro Trigger (mit Long-Press Loop)
  description: >
    Blueprint für ZHA Device Trigger (IKEA E1743 / ähnliche).
    Für Short-Press/Release/Offline können Sequenzen gewählt werden.
    Für Long-Press wird optional eine Loop-Sequenz periodisch wiederholt, bis Release kommt.
  domain: automation

  input:
    zha_device:
      name: ZHA Gerät
      selector:
        device:
          integration: zha

    # Short press actions
    on_short_actions:
      name: Short Press – turn_on
      default: []
      selector:
        action: {}

    off_short_actions:
      name: Short Press – turn_off
      default: []
      selector:
        action: {}

    # Long press up (dim_up)
    up_long_start_actions:
      name: Long Press (dim_up) – Start (einmalig)
      description: Wird einmalig beim Start des Long-Press ausgeführt.
      default: []
      selector:
        action: {}

    up_long_loop_actions:
      name: Long Press (dim_up) – Loop (wiederholt)
      description: Wird periodisch wiederholt, solange gedrückt gehalten wird.
      default: []
      selector:
        action: {}

    up_release_actions:
      name: Long Release – dim_up
      default: []
      selector:
        action: {}

    # Long press down (dim_down)
    down_long_start_actions:
      name: Long Press (dim_down) – Start (einmalig)
      description: Wird einmalig beim Start des Long-Press ausgeführt.
      default: []
      selector:
        action: {}

    down_long_loop_actions:
      name: Long Press (dim_down) – Loop (wiederholt)
      description: Wird periodisch wiederholt, solange gedrückt gehalten wird.
      default: []
      selector:
        action: {}

    down_release_actions:
      name: Long Release – dim_down
      default: []
      selector:
        action: {}

    offline_actions:
      name: Device Offline
      default: []
      selector:
        action: {}

    # Loop tuning
    loop_enabled:
      name: Loop aktivieren
      default: true
      selector:
        boolean: {}

    loop_delay_ms:
      name: Loop Intervall (ms)
      description: Wartezeit zwischen zwei Loop-Ausführungen.
      default: 250
      selector:
        number:
          min: 50
          max: 2000
          step: 50
          unit_of_measurement: ms
          mode: slider

    loop_max_repeats:
      name: Maximale Loop-Wiederholungen
      description: Sicherheitslimit, falls Release nicht kommt.
      default: 500
      selector:
        number:
          min: 1
          max: 2000
          step: 1
          mode: slider

mode: restart
max_exceeded: silent

triggers:
  - domain: zha
    device_id: !input zha_device
    type: remote_button_short_press
    subtype: turn_on
    id: short_on
    trigger: device

  - domain: zha
    device_id: !input zha_device
    type: remote_button_short_press
    subtype: turn_off
    id: short_off
    trigger: device

  - domain: zha
    device_id: !input zha_device
    type: remote_button_long_press
    subtype: dim_up
    id: long_up
    trigger: device

  - domain: zha
    device_id: !input zha_device
    type: remote_button_long_release
    subtype: dim_up
    id: release_up
    trigger: device

  - domain: zha
    device_id: !input zha_device
    type: remote_button_long_press
    subtype: dim_down
    id: long_down
    trigger: device

  - domain: zha
    device_id: !input zha_device
    type: remote_button_long_release
    subtype: dim_down
    id: release_down
    trigger: device

  - domain: zha
    device_id: !input zha_device
    type: device_offline
    subtype: device_offline
    id: device_offline
    trigger: device

actions:
  - choose:
      - conditions:
          - condition: trigger
            id: short_on
        sequence: !input on_short_actions

      - conditions:
          - condition: trigger
            id: short_off
        sequence: !input off_short_actions

      - conditions:
          - condition: trigger
            id: long_up
        sequence:
          - sequence: !input up_long_start_actions
          - choose:
              - conditions:
                  - condition: template
                    value_template: "{{ (loop_enabled | bool) and ((loop_delay_ms | int) > 0) }}"
                sequence:
                  - repeat:
                      while:
                        - condition: template
                          value_template: "{{ repeat.index <= (loop_max_repeats | int) }}"
                      sequence:
                        - sequence: !input up_long_loop_actions
                        - delay:
                            milliseconds: !input loop_delay_ms
            default:
              - sequence: !input up_long_loop_actions

      - conditions:
          - condition: trigger
            id: release_up
        sequence: !input up_release_actions

      - conditions:
          - condition: trigger
            id: long_down
        sequence:
          - sequence: !input down_long_start_actions
          - choose:
              - conditions:
                  - condition: template
                    value_template: "{{ (loop_enabled | bool) and ((loop_delay_ms | int) > 0) }}"
                sequence:
                  - repeat:
                      while:
                        - condition: template
                          value_template: "{{ repeat.index <= (loop_max_repeats | int) }}"
                      sequence:
                        - sequence: !input down_long_loop_actions
                        - delay:
                            milliseconds: !input loop_delay_ms
            default:
              - sequence: !input down_long_loop_actions

      - conditions:
          - condition: trigger
            id: release_down
        sequence: !input down_release_actions

      - conditions:
          - condition: trigger
            id: device_offline
        sequence: !input offline_actions
