blueprint:
  name: ZHA Remote – Device Trigger (IKEA, Philips, Aqara)
  description: >
    Blueprint für ZHA Remotes mit Device-Triggern.
    Unterstützt Short Press, Long Press mit Loop und Release.
    Mode restart sorgt dafür, dass Long-Press-Loop bei Release stoppt.
  domain: automation
  source_url: https://github.com/ThoSchGer/Homeassistant/blob/main/Automatisierung/zha_remote_actions_per_trigger.yaml

  input:
    # ===== Geräteauswahl =====
    zha_device:
      name: ZHA Remote Gerät
      description: Das ZHA-Gerät (z.B. IKEA Tradfri, Philips Hue Remote)
      selector:
        device:
          integration: zha
          multiple: false

    # ===== Short Press Aktionen =====
    on_short_actions:
      name: Short Press ON (oben)
      description: Aktionen beim kurzen Drücken der oberen Taste
      default: []
      selector:
        action: {}

    off_short_actions:
      name: Short Press OFF (unten)
      description: Aktionen beim kurzen Drücken der unteren Taste
      default: []
      selector:
        action: {}

    # ===== Long Press UP Aktionen =====
    up_long_start_actions:
      name: Long Press UP – Start
      description: Wird einmalig beim Start des Long-Press oben ausgeführt
      default: []
      selector:
        action: {}

    up_long_loop_actions:
      name: Long Press UP – Loop
      description: Wird während des Long-Press oben wiederholt ausgeführt
      default: []
      selector:
        action: {}

    up_release_actions:
      name: Release UP
      description: Aktionen beim Loslassen der oberen Taste
      default: []
      selector:
        action: {}

    # ===== Long Press DOWN Aktionen =====
    down_long_start_actions:
      name: Long Press DOWN – Start
      description: Wird einmalig beim Start des Long-Press unten ausgeführt
      default: []
      selector:
        action: {}

    down_long_loop_actions:
      name: Long Press DOWN – Loop
      description: Wird während des Long-Press unten wiederholt ausgeführt
      default: []
      selector:
        action: {}

    down_release_actions:
      name: Release DOWN
      description: Aktionen beim Loslassen der unteren Taste
      default: []
      selector:
        action: {}

    # ===== Loop Konfiguration =====
    loop_enabled:
      name: Loop aktivieren
      description: Long-Press Aktionen wiederholt ausführen
      default: true
      selector:
        boolean: {}

    loop_delay_ms:
      name: Loop Intervall (ms)
      description: Verzögerung zwischen Loop-Wiederholungen
      default: 250
      selector:
        number:
          min: 50
          max: 2000
          step: 50
          unit_of_measurement: ms
          mode: slider

    loop_max_repeats:
      name: Maximale Loop-Wiederholungen
      description: Sicherheitsgrenze für Loop-Durchläufe
      default: 500
      selector:
        number:
          min: 1
          max: 2000
          step: 1
          mode: slider

mode: restart
max_exceeded: silent

trigger:
  # Short Press UP (ON)
  - platform: device
    device_id: !input zha_device
    domain: zha
    type: remote_button_short_press
    subtype: turn_on
    id: short_up

  # Short Press DOWN (OFF)
  - platform: device
    device_id: !input zha_device
    domain: zha
    type: remote_button_short_press
    subtype: turn_off
    id: short_down

  # Long Press UP
  - platform: device
    device_id: !input zha_device
    domain: zha
    type: remote_button_long_press
    subtype: dim_up
    id: long_up

  # Long Press DOWN
  - platform: device
    device_id: !input zha_device
    domain: zha
    type: remote_button_long_press
    subtype: dim_down
    id: long_down

  # Release UP
  - platform: device
    device_id: !input zha_device
    domain: zha
    type: remote_button_long_release
    subtype: dim_up
    id: release_up

  # Release DOWN
  - platform: device
    device_id: !input zha_device
    domain: zha
    type: remote_button_long_release
    subtype: dim_down
    id: release_down

action:
  - choose:
      # === Short Press UP ===
      - conditions:
          - condition: trigger
            id: short_up
        sequence: !input on_short_actions

      # === Short Press DOWN ===
      - conditions:
          - condition: trigger
            id: short_down
        sequence: !input off_short_actions

      # === Long Press UP ===
      - conditions:
          - condition: trigger
            id: long_up
        sequence:
          - sequence: !input up_long_start_actions
          - if:
              - condition: template
                value_template: "{{ loop_enabled }}"
            then:
              - repeat:
                  while:
                    - condition: template
                      value_template: "{{ repeat.index <= loop_max_repeats }}"
                  sequence:
                    - sequence: !input up_long_loop_actions
                    - delay:
                        milliseconds: !input loop_delay_ms
            else:
              - sequence: !input up_long_loop_actions

      # === Long Press DOWN ===
      - conditions:
          - condition: trigger
            id: long_down
        sequence:
          - sequence: !input down_long_start_actions
          - if:
              - condition: template
                value_template: "{{ loop_enabled }}"
            then:
              - repeat:
                  while:
                    - condition: template
                      value_template: "{{ repeat.index <= loop_max_repeats }}"
                  sequence:
                    - sequence: !input down_long_loop_actions
                    - delay:
                        milliseconds: !input loop_delay_ms
            else:
              - sequence: !input down_long_loop_actions

      # === Release UP ===
      - conditions:
          - condition: trigger
            id: release_up
        sequence: !input up_release_actions

      # === Release DOWN ===
      - conditions:
          - condition: trigger
            id: release_down
        sequence: !input down_release_actions
