blueprint:
  name: ZHA Remote – Universal (zha_event)
  description: >
    Universeller Blueprint für ZHA Remotes über zha_event.
    Funktioniert mit allen ZHA-Geräten, unabhängig von Device-Trigger-Support.
    Unterstützt Short Press, Long Press und Release.
  domain: automation
  source_url: https://github.com/ThoSchGer/Homeassistant/blob/main/Automatisierung/zha_remote_actions_per_trigger.yaml

  input:
    # ===== Geräteauswahl =====
    zha_device:
      name: ZHA Remote Gerät
      description: Das ZHA-Gerät (z.B. IKEA Tradfri, Philips Hue Remote)
      selector:
        device:
          integration: zha
          multiple: false
    
    # ===== Command Matching =====
    command_short_on:
      name: Command für Short ON
      description: ZHA command für kurzen Druck oben (z.B. "on", "toggle")
      default: "on"
      selector:
        text:
    
    command_short_off:
      name: Command für Short OFF
      description: ZHA command für kurzen Druck unten (z.B. "off", "toggle")
      default: "off"
      selector:
        text:
    
    command_long_up:
      name: Command für Long UP
      description: ZHA command für langen Druck oben (z.B. "move_with_on_off", "step_with_on_off")
      default: "move_with_on_off"
      selector:
        text:
    
    command_long_down:
      name: Command für Long DOWN
      description: ZHA command für langen Druck unten (z.B. "move", "step")
      default: "move"
      selector:
        text:
    
    command_release:
      name: Command für Release
      description: ZHA command für Loslassen (z.B. "stop", "stop_with_on_off")
      default: "stop_with_on_off"
      selector:
        text:

    # ===== Short Press Aktionen =====
    on_short_actions:
      name: Short Press ON (oben)
      description: Aktionen beim kurzen Drücken der oberen Taste
      default: []
      selector:
        action: {}

    off_short_actions:
      name: Short Press OFF (unten)
      description: Aktionen beim kurzen Drücken der unteren Taste
      default: []
      selector:
        action: {}

    # ===== Long Press Aktionen =====
    up_long_actions:
      name: Long Press UP
      description: Aktionen beim langen Drücken der oberen Taste
      default: []
      selector:
        action: {}

    down_long_actions:
      name: Long Press DOWN
      description: Aktionen beim langen Drücken der unteren Taste
      default: []
      selector:
        action: {}

    # ===== Release Aktionen =====
    release_actions:
      name: Release
      description: Aktionen beim Loslassen (egal ob UP oder DOWN)
      default: []
      selector:
        action: {}

    # ===== Debug =====
    debug_mode:
      name: Debug-Modus
      description: Zeigt erkannte Commands im System-Log (hilft beim Troubleshooting)
      default: false
      selector:
        boolean: {}

mode: restart
max_exceeded: silent

trigger:
  - platform: event
    event_type: zha_event
    event_data:
      device_id: !input zha_device

variables:
  command: "{{ trigger.event.data.command }}"
  args: "{{ trigger.event.data.args | default([]) }}"
  cmd_short_on: !input command_short_on
  cmd_short_off: !input command_short_off
  cmd_long_up: !input command_long_up
  cmd_long_down: !input command_long_down
  cmd_release: !input command_release

action:
  # Debug Logging
  - if:
      - condition: template
        value_template: "{{ debug_mode | default(false) }}"
    then:
      - service: system_log.write
        data:
          message: |
            ZHA Remote Debug:
            Command: {{ command }}
            Args: {{ args }}
            Args[0]: {{ args[0] if args | length > 0 else 'none' }}
            Match Short ON: {{ command == cmd_short_on }}
            Match Short OFF: {{ command == cmd_short_off }}
            Match Long UP: {{ command == cmd_long_up and args | length > 0 and args[0] in [0, '0', 'MoveMode.Up'] }}
            Match Long DOWN: {{ command == cmd_long_down and args | length > 0 and args[0] in [1, '1', 'MoveMode.Down'] }}
            Match Release: {{ command == cmd_release }}
          level: warning

  - choose:
      # === Short Press ON ===
      - conditions:
          - condition: template
            value_template: "{{ command == cmd_short_on }}"
        sequence: !input on_short_actions

      # === Short Press OFF ===
      - conditions:
          - condition: template
            value_template: "{{ command == cmd_short_off }}"
        sequence: !input off_short_actions

      # === Long Press UP ===
      - conditions:
          - condition: template
            value_template: "{{ command == cmd_long_up }}"
          - condition: template
            value_template: "{{ args | length > 0 and args[0] in [0, '0', 'MoveMode.Up'] }}"
        sequence: !input up_long_actions

      # === Long Press DOWN ===
      - conditions:
          - condition: template
            value_template: "{{ command == cmd_long_down }}"
          - condition: template
            value_template: "{{ args | length > 0 and args[0] in [1, '1', 'MoveMode.Down'] }}"
        sequence: !input down_long_actions

      # === Release ===
      - conditions:
          - condition: template
            value_template: "{{ command == cmd_release }}"
        sequence: !input release_actions
