blueprint:
  name: ZHA Remote – Aktionen pro Device-Trigger (mit Long-Press Loop)
  description: >
    Robuster Blueprint für ZHA Remotes über Device-Trigger.
    Pro Trigger (short/long/release up/down) können Sequenzen definiert werden.
    Long-Press kann in einer Loop wiederholt werden, bis Release kommt (mode restart).
    Mit Debug-Modus und optionalen Bedingungen.
    Kompatibel mit: IKEA Tradfri, Philips Hue, Aqara und anderen ZHA Remotes.
  domain: automation
  source_url: https://github.com/ThoSchGer/Homeassistant/blob/main/Automatisierung/zha_remote_actions_per_trigger.yaml

  input:
    # ===== Geräteauswahl =====
    zha_device:
      name: ZHA Gerät
      description: Das ZHA-Gerät (z.B. Remote, Schalter), das überwacht werden soll
      selector:
        device:
          integration: zha
          multiple: false

    # ===== Short Press Aktionen =====
    on_short_actions:
      name: Short Up (ON)
      description: Aktionen beim kurzen Drücken der oberen Taste (z.B. Licht einschalten)
      default: []
      selector:
        action: {}

    off_short_actions:
      name: Short Down (OFF)
      description: Aktionen beim kurzen Drücken der unteren Taste (z.B. Licht ausschalten)
      default: []
      selector:
        action: {}

    # ===== Long Press Up Aktionen =====
    up_long_start_actions:
      name: Long Up – Start (einmalig)
      description: Wird einmalig beim Start des Long-Press ausgeführt (z.B. Dimmen starten)
      default: []
      selector:
        action: {}

    up_long_loop_actions:
      name: Long Up – Loop (wiederholt)
      description: Wird während des Long-Press wiederholt ausgeführt (z.B. Helligkeit erhöhen)
      default: []
      selector:
        action: {}

    up_release_actions:
      name: Release Up
      description: Aktionen beim Loslassen der oberen Taste nach Long-Press
      default: []
      selector:
        action: {}

    # ===== Long Press Down Aktionen =====
    down_long_start_actions:
      name: Long Down – Start (einmalig)
      description: Wird einmalig beim Start des Long-Press ausgeführt (z.B. Dimmen starten)
      default: []
      selector:
        action: {}

    down_long_loop_actions:
      name: Long Down – Loop (wiederholt)
      description: Wird während des Long-Press wiederholt ausgeführt (z.B. Helligkeit verringern)
      default: []
      selector:
        action: {}

    down_release_actions:
      name: Release Down
      description: Aktionen beim Loslassen der unteren Taste nach Long-Press
      default: []
      selector:
        action: {}

    # ===== Loop Konfiguration =====
    loop_enabled:
      name: Loop aktivieren
      description: Long-Press Aktionen wiederholt ausführen (für Dimming etc.)
      default: true
      selector:
        boolean: {}

    loop_delay_ms:
      name: Loop Intervall (ms)
      description: Verzögerung zwischen Loop-Wiederholungen (niedriger = schneller)
      default: 250
      selector:
        number:
          min: 50
          max: 2000
          step: 50
          unit_of_measurement: ms
          mode: slider

    loop_max_repeats:
      name: Maximale Loop-Wiederholungen
      description: Sicherheitsgrenze für Loop-Durchläufe (verhindert Endlosschleifen)
      default: 500
      selector:
        number:
          min: 1
          max: 2000
          step: 1
          mode: slider

    # ===== Debug & Erweitert =====
    debug_mode:
      name: Debug-Modus
      description: Aktiviert Logging für Troubleshooting (zeigt erkannte Events im Log)
      default: false
      selector:
        boolean: {}

    enable_conditions:
      name: Bedingungen aktivieren
      description: Optional - Bedingungen die erfüllt sein müssen (z.B. nur nachts)
      default: []
      selector:
        condition: {}

mode: restart
max_exceeded: silent

triggers:
  # Short Press Up (ON)
  - trigger: device
    device_id: !input zha_device
    domain: zha
    type: remote_button_short_press
    subtype: turn_on
    id: short_up

  # Short Press Down (OFF)
  - trigger: device
    device_id: !input zha_device
    domain: zha
    type: remote_button_short_press
    subtype: turn_off
    id: short_down

  # Long Press Up (Dim Up)
  - trigger: device
    device_id: !input zha_device
    domain: zha
    type: remote_button_long_press
    subtype: dim_up
    id: long_up

  # Long Press Down (Dim Down)
  - trigger: device
    device_id: !input zha_device
    domain: zha
    type: remote_button_long_press
    subtype: dim_down
    id: long_down

  # Long Release Up
  - trigger: device
    device_id: !input zha_device
    domain: zha
    type: remote_button_long_release
    subtype: dim_up
    id: release_up

  # Long Release Down
  - trigger: device
    device_id: !input zha_device
    domain: zha
    type: remote_button_long_release
    subtype: dim_down
    id: release_down

variables:
  # Trigger ID für Action-Matching
  trigger_id: "{{ trigger.id | default('') }}"
  
  # Debug Helper
  is_debug: "{{ debug_mode | default(false) | bool }}"

actions:
  # Debug Logging
  - if:
      - condition: template
        value_template: "{{ is_debug }}"
    then:
      - service: system_log.write
        data:
          message: |
            ZHA Remote Device-Trigger erkannt:
            Trigger ID: {{ trigger_id }}
            Platform: {{ trigger.platform | default('unknown') }}
            Device ID: {{ trigger.device_id | default('unknown') }}
            Type: {{ trigger.type | default('unknown') }}
            Subtype: {{ trigger.subtype | default('unknown') }}
          level: info

  # Optionale Bedingungen prüfen
  - condition: and
    conditions: !input enable_conditions

  # Device-Trigger-basierte Aktionen
  - choose:
      # === Short Press Up (ON) ===
      - conditions:
          - condition: template
            value_template: "{{ trigger_id == 'short_up' }}"
        sequence: !input on_short_actions

      # === Short Press Down (OFF) ===
      - conditions:
          - condition: template
            value_template: "{{ trigger_id == 'short_down' }}"
        sequence: !input off_short_actions

      # === Long Press Up (Dim Up) ===
      - conditions:
          - condition: template
            value_template: "{{ trigger_id == 'long_up' }}"
        sequence:
          # Start-Aktion einmalig ausführen
          - sequence: !input up_long_start_actions
          # Loop-Logik mit verbesserter Fehlerbehandlung
          - choose:
              - conditions:
                  - condition: template
                    value_template: "{{ (loop_enabled | default(false)) | bool }}"
                sequence:
                  - repeat:
                      while:
                        - condition: template
                          value_template: "{{ repeat.index <= ((loop_max_repeats | default(500)) | int) }}"
                      sequence:
                        - sequence: !input up_long_loop_actions
                        - delay:
                            milliseconds: "{{ (loop_delay_ms | default(250)) | int }}"
            default:
              # Einmalige Ausführung wenn Loop deaktiviert
              - sequence: !input up_long_loop_actions

      # === Long Press Down (Dim Down) ===
      - conditions:
          - condition: template
            value_template: "{{ trigger_id == 'long_down' }}"
        sequence:
          # Start-Aktion einmalig ausführen
          - sequence: !input down_long_start_actions
          # Loop-Logik mit verbesserter Fehlerbehandlung
          - choose:
              - conditions:
                  - condition: template
                    value_template: "{{ (loop_enabled | default(false)) | bool }}"
                sequence:
                  - repeat:
                      while:
                        - condition: template
                          value_template: "{{ repeat.index <= ((loop_max_repeats | default(500)) | int) }}"
                      sequence:
                        - sequence: !input down_long_loop_actions
                        - delay:
                            milliseconds: "{{ (loop_delay_ms | default(250)) | int }}"
            default:
              # Einmalige Ausführung wenn Loop deaktiviert
              - sequence: !input down_long_loop_actions

      # === Release Up ===
      - conditions:
          - condition: template
            value_template: "{{ trigger_id == 'release_up' }}"
        sequence: !input up_release_actions

      # === Release Down ===
      - conditions:
          - condition: template
            value_template: "{{ trigger_id == 'release_down' }}"
        sequence: !input down_release_actions
